---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
  namespace: database
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: keycloak-db-credentials
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .KEYCLOAK_DB_USER }}"
        password: "{{ .KEYCLOAK_DB_PASS }}"
  dataFrom:
    - extract:
        key: keycloak