---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./service.yaml
  - ./resume-api-secret.yaml
  - ./n8n-secret.yaml
  - ./maybe-secret.yaml
  - ./keycloak-secret.yaml
  - ./revysr-dev-secret.yaml