---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: revysr-api-secret
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: revysr-api-secret
    template:
      engineVersion: v2
      data:
        KEYCLOAK_CONFIDENTIAL_CLIENT_SECRET: "{{ .REVYSR_KEYCLOAK_CONFIDENTIAL_CLIENT_SECRET }}"
        FREEMIUS_PRODUCT_ID: "{{ .FREEMIUS_PRODUCT_ID }}"
        FREEMIUS_SECRET_KEY: "{{ .FREEMIUS_SECRET_KEY }}"
        FREEMIUS_AUTH: "{{ .FREEMIUS_AUTH }}"
  dataFrom:
    - extract:
        key: revysr-dev

