---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  # - ./cross-seed/ks.yaml
  - ./fusion/ks.yaml
  - ./home-assistant/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./maintainerr/ks.yaml
  # - ./maybe/ks.yaml
  - ./mosquitto/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  # - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml