---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./resume-api-database.yaml
  - ./n8n-database.yaml
  - ./maybe-database.yaml
  - ./keycloak-database.yaml
  - ./revysr-dev-database.yaml