---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: revysr-dev
  namespace: database
spec:
  name: revysr_dev
  owner: revysr_dev_user
  cluster:
    name: postgres