---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: revysr-frontend
  namespace: dev-app
spec:
  endpoints:
    - dnsName: "dev.${APP_DEV_SECRET_DOMAIN}"
      recordType: CNAME
      targets: ["external.${APP_DEV_SECRET_DOMAIN}"]

