---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: yarp-image
spec:
  interval: 5m
  url: oci://ghcr.io/codevannin/revysr
  ref:
    tag: latest
  secretRef:
    name: ghcr-credentials

