---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-http-config
data:
  http.yaml: |
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.1.2.0/24      # Node network
        - 10.42.0.0/16     # Pod network
        - 10.43.0.0/16     # Service network
