apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    APP_DEV_SECRET_DOMAIN: ENC[AES256_GCM,data:uhNgWZZ65tjLbw==,iv:SIYbTXyhu4wF8iV4VVWtP/6+vvzaKRGN+xr2YSWHndI=,tag:gpheTpIXXgaaW74wwYWUdg==,type:str]
    APP_DEV_GITHUB_REPO: ENC[AES256_GCM,data:eC7DoUhHHYYZT4hwC9pjJWE29HqctZlWSm0oylMxrBZsAVaf,iv:ClaftZdqgS/zX8Dd5AkYd2LBwAOuoohnSYgf9KgdKs4=,tag:6+TraYDAo2hpPs4+U92AwQ==,type:str]
sops:
    age:
        - recipient: age1gm4pzyutmqq4g38e32xjf2re7hq5m0nfuymstvwy3hp9xzgwkg7qu6vwc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYWtGVlZQMG0wYWJpTmR2
            b0pCa3BlYVZTYUhzYklINGcwTC9pSStCbW1zCmN0UzdKOEhZM1FSVE1NQ212YTBD
            eDRQT1B4TVhMQ1QyM3ZDM2c1T1VUWWMKLS0tIEZpMmpxNkpIUUZLMGw2b3lJWlhQ
            QjZFLzJubDFNcmR3czA2b2tMb2FRcDQKR77B5/8giBed3StMQN4LUqg7lf9j+sGt
            vcYDRYthnunj/LkeYlGg6HHJUofS6WiyC2dt6t8Ns1XmU1/pyHnRbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T17:39:05Z"
    mac: ENC[AES256_GCM,data:HQsMKLUuQQ0pE0iZzowR+eXKY9p7pI/fnX9ZGntjILI3iwPFsRcLfahRJJUmrQaPvsKvnvgFkc4NHj0Z64OsJVBjX1NVFi2RwYnsWQmyRdikVfKT/R9XbMexfyY5eipR/B6TPMbvSOt0YMp8POy/NyU0bM7d30QYn9SyCVM/RN0=,iv:11eU6fU5fR1HjLT4osNDdIRgzVqXpxoZQeqo0RxSQ4M=,tag:j5m6V0JN8OGZI/O4rnsQ+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
