apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    APP_DEV_SECRET_DOMAIN: ENC[AES256_GCM,data:uhNgWZZ65tjLbw==,iv:SIYbTXyhu4wF8iV4VVWtP/6+vvzaKRGN+xr2YSWHndI=,tag:gpheTpIXXgaaW74wwYWUdg==,type:str]
sops:
    age:
        - recipient: age1gm4pzyutmqq4g38e32xjf2re7hq5m0nfuymstvwy3hp9xzgwkg7qu6vwc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYWtGVlZQMG0wYWJpTmR2
            b0pCa3BlYVZTYUhzYklINGcwTC9pSStCbW1zCmN0UzdKOEhZM1FSVE1NQ212YTBD
            eDRQT1B4TVhMQ1QyM3ZDM2c1T1VUWWMKLS0tIEZpMmpxNkpIUUZLMGw2b3lJWlhQ
            QjZFLzJubDFNcmR3czA2b2tMb2FRcDQKR77B5/8giBed3StMQN4LUqg7lf9j+sGt
            vcYDRYthnunj/LkeYlGg6HHJUofS6WiyC2dt6t8Ns1XmU1/pyHnRbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T10:26:48Z"
    mac: ENC[AES256_GCM,data:LueEGV5tfRphyZOLvPv8dJOFyAl07Sn2SntTyPMXw5CxT5/trZGYHCZLo4aruHk/NPmlu7b+5NzddSFSu4bXT+neSuvP527sDNHa/5oIicwsWz0VR4hjtnO3xU9o9xYVbDIrtjoUHrfU7xFE4yZbwsxSN5DUqHuk9TOPNenMvKo=,iv:J+/oQIEydIPWabtW2jdYtAs05Hww+xQl/0HEuHtpuBg=,tag:hHWR8RX5C95bh+PEO9HOPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
