apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    APP_DEV_SECRET_DOMAIN: ENC[AES256_GCM,data:uhNgWZZ65tjLbw==,iv:SIYbTXyhu4wF8iV4VVWtP/6+vvzaKRGN+xr2YSWHndI=,tag:gpheTpIXXgaaW74wwYWUdg==,type:str]
    APP_DEV_GITHUB_REPO: ENC[AES256_GCM,data:3ejE0XLgk8IXTHsCYTB9ytk3a3VpiEU3/Slc8iA=,iv:+NaodQ6H0NX0Op5hUk5KKZSH7rNU7ukFh9dnt1yLCKo=,tag:EKaaccxB1Bpcw1FiObX9Pw==,type:str]
sops:
    age:
        - recipient: age1gm4pzyutmqq4g38e32xjf2re7hq5m0nfuymstvwy3hp9xzgwkg7qu6vwc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYWtGVlZQMG0wYWJpTmR2
            b0pCa3BlYVZTYUhzYklINGcwTC9pSStCbW1zCmN0UzdKOEhZM1FSVE1NQ212YTBD
            eDRQT1B4TVhMQ1QyM3ZDM2c1T1VUWWMKLS0tIEZpMmpxNkpIUUZLMGw2b3lJWlhQ
            QjZFLzJubDFNcmR3czA2b2tMb2FRcDQKR77B5/8giBed3StMQN4LUqg7lf9j+sGt
            vcYDRYthnunj/LkeYlGg6HHJUofS6WiyC2dt6t8Ns1XmU1/pyHnRbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T12:05:06Z"
    mac: ENC[AES256_GCM,data:CtilfDhB7m5P9w92YbWZTjSdAN/vzjT+3AY8UbqVRyFAEBjvF2J28kWvTzA2FrM6wrVVhVru6vzrC9iMbQRYH7YoenC/iW3X7ldJj+pC0zBzTCmSFBiSmEkvirLBDjjXDb/vN17GMSgAoEqJgTwbFSOFVeiUmDkWEstWEAy82K8=,iv:oE/GSgHZd6LXzJGSs13Gm222teUndtlU+nJ6uuu08dU=,tag:+UhM2mrvwS91XrMQqPY8JQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
