apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:DuRmlRD1GZf1RjdMfadGnsUKCOmpNjJn42EShIV/Mimnzjb5EOMV5uDiLczZscDs1WAlFZvrDIJ6bEEXVfkKLg0H/leLCdd6tcg=,iv:krsUUMh5MA3h1yLmezwSauAsz9xdXxjQpdsRCmdxIcQ=,tag:VKUSz0egsok/YaZQcvhUxA==,type:str]
    APP_DEV_SECRET_DOMAIN: ENC[AES256_GCM,data:uhNgWZZ65tjLbw==,iv:SIYbTXyhu4wF8iV4VVWtP/6+vvzaKRGN+xr2YSWHndI=,tag:gpheTpIXXgaaW74wwYWUdg==,type:str]
sops:
    age:
        - recipient: age1gm4pzyutmqq4g38e32xjf2re7hq5m0nfuymstvwy3hp9xzgwkg7qu6vwc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYWtGVlZQMG0wYWJpTmR2
            b0pCa3BlYVZTYUhzYklINGcwTC9pSStCbW1zCmN0UzdKOEhZM1FSVE1NQ212YTBD
            eDRQT1B4TVhMQ1QyM3ZDM2c1T1VUWWMKLS0tIEZpMmpxNkpIUUZLMGw2b3lJWlhQ
            QjZFLzJubDFNcmR3czA2b2tMb2FRcDQKR77B5/8giBed3StMQN4LUqg7lf9j+sGt
            vcYDRYthnunj/LkeYlGg6HHJUofS6WiyC2dt6t8Ns1XmU1/pyHnRbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T10:09:18Z"
    mac: ENC[AES256_GCM,data:4oJEWPIniDcj3FCrcUA1oglBdlgixsNe7whFinps2UvK8A2LmcF2vsYU2UN0zB+ECObx5jeZRKRl8/dewBpevFEpdYj+V2TcYOj4achOSzLa5KUvP5jbfc4N+mizW+qShGWCPg2+ClJNVAExVOTDtm7L7iB5npobUn6PVjHOT6s=,iv:4XBR/EYlwejmmve+jjvD6mCOD4kg61sdyW/yQeNg7rs=,tag:637EDUM4qB1pL8GsAWgZVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
