---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-dev-production
spec:
  secretName: app-dev-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: ${APP_DEV_SECRET_DOMAIN}
  dnsNames: ["${APP_DEV_SECRET_DOMAIN}", "*.${APP_DEV_SECRET_DOMAIN}"]
